---
- name: Cria diretório da aplicação no servidor
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: "0755"

- name: Sincroniza arquivos do docker para o servidor
  ansible.posix.synchronize:
    src: "{{ setup_dca_local_docker_dir }}/"
    dest: "{{ app_dir }}/"
    recursive: true
    delete: true

- name: Inicia Traefik e Banco de Dados
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
    services:
      - traefik
      - database
      - backend
      - frontend
      - landing-page
    recreate: auto
